apiVersion: v1
kind: Service
metadata:
  name: samplewebapp
  labels:
    app: samplewebapp
spec:
  ports:
    - port: 80 
  selector:
    app: samplewebapp
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: samplewebapp
  name: samplewebapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: samplewebapp
    spec:
      containers:
      - image: #{IMAGETAG}#
        name: samplewebapp
        ports:
        - containerPort: 80
          protocol: TCP
